### ISSUE TITLE
fffff

### ISSUE THREAD

**Issue by AGES-LDEO** [AGESLDEO/pychron#1]
active branch=None

active analyses=

```
Traceback (most recent call last):
  File "/anaconda/envs/pychron/lib/python2.7/site-packages/pyface/ui/qt4/action/action_item.py", line 163, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/anaconda/envs/pychron/lib/python2.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/Sidney/Programming/pychron/pychron/pipeline/tasks/actions.py", line 127, in perform
    task = app.get_task('pychron.pipeline.task')
  File "/Users/Sidney/Programming/pychron/pychron/envisage/tasks/base_tasks_application.py", line 109, in get_task
    win = self.create_window(w)
  File "/anaconda/envs/pychron/lib/python2.7/site-packages/envisage/ui/tasks/tasks_application.py", line 212, in create_window
    window.set_window_layout(layout)
  File "/anaconda/envs/pychron/lib/python2.7/site-packages/pyface/tasks/task_window.py", line 333, in set_window_layout
    self.activate_task(state.task)
  File "/anaconda/envs/pychron/lib/python2.7/site-packages/pyface/tasks/task_window.py", line 156, in activate_task
    task.activated()
  File "/Users/Sidney/Programming/pychron/pychron/pipeline/tasks/task.py", line 108, in activated
    foo
NameError: global name 'foo' is not defined

```

**Comment by stephen-e-cox** [comment]
Test bug report.
