### ISSUE TITLE
Update does not work

### ISSUE THREAD

**Issue by sidneyhemming** [AGESLDEO/pychron#3]
active branch=None

active analyses=

Cannot update from preferences :'(

```
Traceback (most recent call last):
  File "/Users/sidneyhemming/anaconda2/envs/pychron3/lib/python3.4/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/sidneyhemming/PycharmProjects/pychron3/pychron/updater/tasks/update_preferences.py", line 147, in _pull_button_fired
    self._updater.pull(self.branch, inform=self._initialized)
  File "/Users/sidneyhemming/PycharmProjects/pychron3/pychron/updater/tasks/update_preferences.py", line 41, in pull
    origin = repo.remote('origin')
AttributeError: 'NoneType' object has no attribute 'remote'

```

**Comment by stephen-e-cox** [comment]
The update plugin requires storing the source code in the .pychron.0 folder.
